global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG #INFO, WARNING, ERROR, CRITICAL
  format: json  # common, json, logfmt
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/access.log

# Only accessible on LAN
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: 
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # Where to store acme.json locally in the container
      storage: /letsencrypt/acme.json
      keyType: EC256
      dnsChallenge:
        provider: route53
        delayBeforeCheck: "0"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    exposedByDefault: false  # Default is true
